In [1]:
import numpy as np 

In [2]:
array1 = np.array([8, 4, 6, 0, 2])

In [3]:
print(array1)


[8 4 6 0 2]


In [4]:
print(np.array([1, 3, 5, 7, 9]))

[1 3 5 7 9]


In [6]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(A)

[[1 2 3]
 [4 5 6]]


In [31]:
print(A[1][0], A[0][1])

4 2


Problem 1

In [32]:
A = np.array([[3, -1, 4], [1, 5, -9]])


In [33]:
A

array([[ 3, -1,  4],
       [ 1,  5, -9]])

In [34]:
B = np.array([[2, 6, -5, 3], [5, -8 , 9 , 7], [9, -3, -2, -3]])

In [35]:
B

array([[ 2,  6, -5,  3],
       [ 5, -8,  9,  7],
       [ 9, -3, -2, -3]])

In [36]:
C = A @ B


In [37]:
C


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [38]:
C = np.dot(A, B)

In [39]:
C

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [61]:
x, y = np.array([1, 2, 3]), np.array([4, 5, 6])

In [52]:
x 

array([1, 2, 3])

In [53]:
x + 10

array([11, 12, 13])

In [54]:
x = x + 10 


In [55]:
x 

array([11, 12, 13])

In [56]:
x = x * 100

In [57]:
x

array([1100, 1200, 1300])

In [58]:
x = x / 100 - 10

In [59]:
x 

array([1., 2., 3.])

In [64]:
x, y = np.array([1, 2, 3]), np.array([4, 5, 6])

In [66]:
x + y 

array([5, 7, 9])

In [67]:
x + y * 100

array([401, 502, 603])

In [68]:
x

array([1, 2, 3])

In [69]:
x * y * x 

array([ 4, 20, 54])

In [70]:
A = np.array([[3, 1, 4], [1, 5 , 9], [-5, 3, 1]])


In [71]:
A

array([[ 3,  1,  4],
       [ 1,  5,  9],
       [-5,  3,  1]])

In [72]:
A3 = np.dot(np.dot(A, A), A)

In [73]:
A3


array([[-135,  165,  165],
       [-348,  402,  387],
       [ -78,   72,   57]])

In [74]:
A2 = np.dot(A, A)

In [77]:
rv = - A3 + 9*A2 - 15*A

In [78]:
rv

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [79]:
arr1 = np.eye(3)

In [80]:
arr1


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
arr2 = np.ones(4)

In [82]:
arr2


array([1., 1., 1., 1.])

In [85]:
arr2 = np.ones((4, 4))

In [86]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
arr3 = np.zeros((5,5), dtype=np.int)

In [88]:
arr3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [89]:
arr4 = np.ones_like(arr3)

In [90]:
arr4

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [91]:
arr5 = np.zeros_like(arr2)

In [92]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
arr6 = np.full((6,6), "Hi")

In [94]:
arr6

array([['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi']], dtype='<U2')

In [95]:
arr5 = arr5.astype(np.int)

In [96]:
arr5


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [97]:
arr5 = arr5.astype(np.float)

In [98]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
p3_arr1 = np.ones((7,7), dtype=np.int)
p3_arr1 = np.triu(p3_arr1)

In [103]:
p3_arr1

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1]])

In [106]:
p3_arr1 = np.triu((1,1,1,1,1,1,1))

In [107]:
p3_arr1

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1]])

In [115]:
p3_arr2 = np.zeros((7,7), dtype=np.int)
p3_arr2 = p3_arr2 + np.triu((5,5,5,5,5,5,5))
p3_arr2 = p3_arr2 + np.tril((-1,-1,-1,-1,-1,-1,-1))
p3_arr2 = p3_arr2 + np.diag((-5,-5,-5,-5,-5,-5,-5))
p3_arr2

array([[-1,  5,  5,  5,  5,  5,  5],
       [-1, -1,  5,  5,  5,  5,  5],
       [-1, -1, -1,  5,  5,  5,  5],
       [-1, -1, -1, -1,  5,  5,  5],
       [-1, -1, -1, -1, -1,  5,  5],
       [-1, -1, -1, -1, -1, -1,  5],
       [-1, -1, -1, -1, -1, -1, -1]])

In [118]:
rv = np.dot(np.dot(p3_arr1,p3_arr2), p3_arr1)
print(rv)

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


In [130]:
arr = np.arange(-10, 10, 1)
print(arr)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


In [129]:
def negtozero(arr1):
    '''
    Problem 4. Write a function that accepts a single array as input. 
    Make a copy of the array, then use fancy indexing to set all 
    negative entries of the copy to 0. Return the copy.
    '''
    arr = np.copy(arr1)
    mask = arr <= 0
    arr[mask] = 0
    return arr
    

In [131]:
print(negtozero(arr))

[0 0 0 0 0 0 0 0 0 0 0 1 2 3 4 5 6 7 8 9]


In [132]:
arr = np.arange(0, 60, 1)

In [133]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [134]:
arr.reshape(3, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59]])

In [135]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [136]:
arr.reshape(10, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [137]:
arr = arr.reshape(10, -1)

In [138]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [139]:
slicer = arr[:, 0]

In [140]:
slicer

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [147]:
A = np.array([0,2,4,1,3,5]).reshape((2,3))
B = np.tril((3,3,3))
C = np.diag((-2,-2,-2))

In [149]:
l1 = np.hstack((np.zeros((3,3)),A.T, np.diag((1,1,1))))

In [152]:
l2 = np.hstack((A, np.zeros((2,2)), np.zeros((2,3))))

In [154]:
l3 = np.hstack((B, np.zeros((3,2)), C))

In [156]:
rv = np.vstack((l1, l2, l3))

In [157]:
rv

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

In [158]:
def stochastic(arr):
    '''
    A matrix is called row-stochastica if its rows each sum to 1. 
    Stochastic matrices are fundamentally important for finite 
    discrete random processes and some machine learning algorithms.
    
    Write a function than accepts a matrix (as a 2-D array). Divide
    each row of the matrix by the row sum and return the new 
    row-stochastic matrix. Use array broadcasting and the axis 
    argument instead of a loop.
    '''
    sums = arr.sum(axis=1).reshape(-1,1)
    print(sums)
    arr = arr / sums
    return arr    

In [160]:
testarr = np.full((5,5), 1)

In [161]:
testarr


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [163]:
rv = stochastic(testarr)

In [169]:
testarr = np.full((5,5), .2)

In [170]:
rv = stochastic(testarr)

In [171]:
rv

array([[0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2]])

In [172]:
testarr

array([[0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2]])

In [173]:
grid = np.load("grid.npy")

FileNotFoundError: [Errno 2] No such file or directory: 'grid.npy'