In [1]:
import numpy as np 

In [2]:
array1 = np.array([8, 4, 6, 0, 2])

In [3]:
print(array1)


[8 4 6 0 2]


In [4]:
print(np.array([1, 3, 5, 7, 9]))

[1 3 5 7 9]


In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(A)

[[1 2 3]
 [4 5 6]]


In [8]:
print(A[1][0], A[0][1])

4 2


Problem 1

In [9]:
A = np.array([[3, -1, 4], [1, 5, -9]])


In [10]:
A

array([[ 3, -1,  4],
       [ 1,  5, -9]])

In [11]:
B = np.array([[2, 6, -5, 3], [5, -8 , 9 , 7], [9, -3, -2, -3]])

In [12]:
B

array([[ 2,  6, -5,  3],
       [ 5, -8,  9,  7],
       [ 9, -3, -2, -3]])

In [13]:
C = A @ B


In [14]:
C


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [15]:
C = np.dot(A, B)

In [16]:
C

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [17]:
x, y = np.array([1, 2, 3]), np.array([4, 5, 6])

In [18]:
x 

array([1, 2, 3])

In [19]:
x + 10

array([11, 12, 13])

In [20]:
x = x + 10 


In [21]:
x 

array([11, 12, 13])

In [22]:
x = x * 100

In [23]:
x

array([1100, 1200, 1300])

In [24]:
x = x / 100 - 10

In [25]:
x 

array([1., 2., 3.])

In [26]:
x, y = np.array([1, 2, 3]), np.array([4, 5, 6])

In [27]:
x + y 

array([5, 7, 9])

In [28]:
x + y * 100

array([401, 502, 603])

In [29]:
x

array([1, 2, 3])

In [30]:
x * y * x 

array([ 4, 20, 54])

Problem 2

In [31]:
A = np.array([[3, 1, 4], [1, 5 , 9], [-5, 3, 1]])


In [32]:
A

array([[ 3,  1,  4],
       [ 1,  5,  9],
       [-5,  3,  1]])

In [33]:
A3 = np.dot(np.dot(A, A), A)

In [34]:
A3


array([[-135,  165,  165],
       [-348,  402,  387],
       [ -78,   72,   57]])

In [35]:
A2 = np.dot(A, A)

In [36]:
rv = - A3 + 9*A2 - 15*A

In [37]:
rv

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [38]:
arr1 = np.eye(3)

In [39]:
arr1


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
arr2 = np.ones(4)

In [41]:
arr2


array([1., 1., 1., 1.])

In [42]:
arr2 = np.ones((4, 4))

In [43]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
arr3 = np.zeros((5,5), dtype=np.int)

In [45]:
arr3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [46]:
arr4 = np.ones_like(arr3)

In [47]:
arr4

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
arr5 = np.zeros_like(arr2)

In [49]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
arr6 = np.full((6,6), "Hi")

In [51]:
arr6

array([['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi', 'Hi', 'Hi', 'Hi']], dtype='<U2')

In [52]:
arr5 = arr5.astype(np.int)

In [53]:
arr5


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
arr5 = arr5.astype(np.float)

In [55]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Problem 3

Part A

In [56]:
p3_arr1 = np.ones((7,7), dtype=np.int)
p3_arr1 = np.triu(p3_arr1)

In [57]:
p3_arr1

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1]])

In [100]:
p3_arr1 = np.triu((1,1,1,1,1,1,1))

In [101]:
p3_arr1

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1]])

Part B

In [60]:
p3_arr2 = np.zeros((7,7), dtype=np.int)
p3_arr2 = p3_arr2 + np.triu((5,5,5,5,5,5,5))
p3_arr2 = p3_arr2 + np.tril((-1,-1,-1,-1,-1,-1,-1))
p3_arr2 = p3_arr2 + np.diag((-5,-5,-5,-5,-5,-5,-5))
p3_arr2

array([[-1,  5,  5,  5,  5,  5,  5],
       [-1, -1,  5,  5,  5,  5,  5],
       [-1, -1, -1,  5,  5,  5,  5],
       [-1, -1, -1, -1,  5,  5,  5],
       [-1, -1, -1, -1, -1,  5,  5],
       [-1, -1, -1, -1, -1, -1,  5],
       [-1, -1, -1, -1, -1, -1, -1]])

In [61]:
rv = np.dot(np.dot(p3_arr1,p3_arr2), p3_arr1)
print(rv)

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


In [62]:
arr = np.arange(-10, 10, 1)
print(arr)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


Problem 4

In [63]:
def negtozero(arr1):
    '''
    Problem 4. Write a function that accepts a single array as input. 
    Make a copy of the array, then use fancy indexing to set all 
    negative entries of the copy to 0. Return the copy.
    '''
    arr = np.copy(arr1)
    mask = arr <= 0
    arr[mask] = 0
    return arr
    

In [64]:
print(negtozero(arr))

[0 0 0 0 0 0 0 0 0 0 0 1 2 3 4 5 6 7 8 9]


In [65]:
arr = np.arange(0, 60, 1)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [67]:
arr.reshape(3, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59]])

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [69]:
arr.reshape(10, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [70]:
arr = arr.reshape(10, -1)

In [71]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [72]:
slicer = arr[:, 0]

In [73]:
slicer

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

Problem 5

In [74]:
A = np.array([0,2,4,1,3,5]).reshape((2,3))
B = np.tril((3,3,3))
C = np.diag((-2,-2,-2))

In [75]:
l1 = np.hstack((np.zeros((3,3)),A.T, np.diag((1,1,1))))

In [76]:
l2 = np.hstack((A, np.zeros((2,2)), np.zeros((2,3))))

In [77]:
l3 = np.hstack((B, np.zeros((3,2)), C))

In [78]:
rv = np.vstack((l1, l2, l3))

In [79]:
rv

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

Problem 6

In [80]:
def stochastic(arr):
    '''
    A matrix is called row-stochastica if its rows each sum to 1. 
    Stochastic matrices are fundamentally important for finite 
    discrete random processes and some machine learning algorithms.
    
    Write a function than accepts a matrix (as a 2-D array). Divide
    each row of the matrix by the row sum and return the new 
    row-stochastic matrix. Use array broadcasting and the axis 
    argument instead of a loop.
    '''
    sums = arr.sum(axis=1).reshape(-1,1)
    print(sums)
    arr = arr / sums
    return arr    

In [81]:
testarr = np.full((5,5), 1)

In [82]:
testarr


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [83]:
rv = stochastic(testarr)

[[5]
 [5]
 [5]
 [5]
 [5]]


In [84]:
testarr = np.full((5,5), .2)

In [85]:
rv = stochastic(testarr)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [86]:
rv

array([[0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2]])

In [87]:
testarr

array([[0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2]])

Problem 7

In [89]:
grid = np.load("grid.npy")

In [91]:
grid

array([[ 8,  2, 22, 97, 38, 15,  0, 40,  0, 75,  4,  5,  7, 78, 52, 12,
        50, 77, 91,  8],
       [49, 49, 99, 40, 17, 81, 18, 57, 60, 87, 17, 40, 98, 43, 69, 48,
         4, 56, 62,  0],
       [81, 49, 31, 73, 55, 79, 14, 29, 93, 71, 40, 67, 53, 88, 30,  3,
        49, 13, 36, 65],
       [52, 70, 95, 23,  4, 60, 11, 42, 69, 24, 68, 56,  1, 32, 56, 71,
        37,  2, 36, 91],
       [22, 31, 16, 71, 51, 67, 63, 89, 41, 92, 36, 54, 22, 40, 40, 28,
        66, 33, 13, 80],
       [24, 47, 32, 60, 99,  3, 45,  2, 44, 75, 33, 53, 78, 36, 84, 20,
        35, 17, 12, 50],
       [32, 98, 81, 28, 64, 23, 67, 10, 26, 38, 40, 67, 59, 54, 70, 66,
        18, 38, 64, 70],
       [67, 26, 20, 68,  2, 62, 12, 20, 95, 63, 94, 39, 63,  8, 40, 91,
        66, 49, 94, 21],
       [24, 55, 58,  5, 66, 73, 99, 26, 97, 17, 78, 78, 96, 83, 14, 88,
        34, 89, 63, 72],
       [21, 36, 23,  9, 75,  0, 76, 44, 20, 45, 35, 14,  0, 61, 33, 97,
        34, 31, 33, 95],
       [78, 17, 53, 28, 22, 75

In [98]:
def adjproduct(grid):
    '''
    Given a grid of number the function aims to find the greatest product of 
    4 adjacent numbers in any direction, up down left right
    '''
    hori_max = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    vert_max = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:, :])
    rdiag_max = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    ldiag_max = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] * grid[3:,:-3])
    rv = max(hori_max, vert_max, rdiag_max, ldiag_max)
    return rv

In [92]:
np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])

48477312

In [93]:
np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:, :])

51267216

In [94]:
np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])


40304286

In [95]:
np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] * grid[3:,:-3])


70600674

In [96]:
max(np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] * grid[3:,:-3])
, np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:]))

70600674

In [99]:
adjproduct(grid)

70600674