In [2]:
import numpy as np
import pandas as pd 
import scipy.linalg as la
import sympy as sy
from matplotlib import pyplot as plt
from datetime import datetime
from scipy import optimize as opt

In [54]:
def Prob1(Df, D2f, x_0, maxiter, tol):
    x_t = x_0
    for i in range(maxiter): 
        z_t = la.solve(D2f(x_t), Df(x_t).T)
        x_t1 = x_t - z_t
        if (la.norm(Df(x_t1), np.inf) < tol):
            print("woohoo")
            return x_t1, True, i+1
        x_t = x_t1
    print("Convergence Failed")
    return x_t1, False, maxiter

f = opt.rosen
df = opt.rosen_der
d2f = opt.rosen_hess
print(opt.fmin_bfgs(f=f, x0=[-2,2], fprime=df, maxiter=50))
Prob1(df, d2f, [-2, 2], 500, 1.E-10)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 35
         Function evaluations: 42
         Gradient evaluations: 42
[1.00000021 1.00000045]
[-1606  -400]
[-6.02964576 -0.01119396]
[ 3387.08115696 -1751.59948417]
[-6.62166774e-02 -7.14557746e-08]
[ 0.4384666 -0.2192333]
[-8.50794768e-10  0.00000000e+00]
woohoo


(array([1., 1.]), True, 6)

In [78]:
def Prob2(Df, x_0, maxiter, tol):
    x_t = x_0
    A_t1 = np.eye(len(x_0))
    valt = Df(x_t).T
    for i in range(maxiter): 
        print(A_t1)
        print(valt)
        x_t1 = x_t - A_t1 @ valt
        valt1 = Df(x_t1)
        print(x_t1)
        print(valt1)
        if (la.norm(valt1, np.inf) < tol):
            print("woohoo")
            return x_t1, True, i+1
        print("x_t1", x_t1)
        s = x_t1 - x_t
        y = valt1.T - valt
        sty = s.T @ y
        print("y: ", y)
        print("s: ", s)
        term1 = ((sty + y.T @ A_t1 @ y) * np.outer(s, s.T))/((sty)**2)
        print(term1)
        term2 = ((A_t1 @ y @ s.T) + (np.outer(s, y.T) @ A_t1) )/(sty)
        print(term2)
        A_t1 = A_t1 + term1 - term2
        valt = valt1.T
        x_t = np.copy(x_t1)
    print("Convergence Failed")
    return x_t1, False, maxiter

Prob2(df, [1.5, 1.5], 500, 1.E-10)

[[1. 0.]
 [0. 1.]]
[ 451. -150.]
[-449.5  151.5]
[-3.63013962e+10 -4.03797500e+07]
x_t1 [-449.5  151.5]
y:  [-3.63013966e+10 -4.03796000e+07]
s:  [-451.  150.]
[[ 1.00074158 -0.33284088]
 [-0.33284088  0.11070096]]
[[2.0003701  1.00111275]
 [0.66728267 0.9996299 ]]
[[ 3.71483371e-04 -1.33395363e+00]
 [-1.00012355e+00  1.11071054e-01]]
[-3.63013962e+10 -4.03797500e+07]
[-4.03797988e+07 -3.63013961e+10]
[-2.63367457e+25 -3.26112890e+17]
x_t1 [-4.03797988e+07 -3.63013961e+10]
y:  [-2.63367457e+25 -3.26112890e+17]
s:  [-4.03793493e+07 -3.63013963e+10]
[[3.71446200e-04 3.33933457e-01]
 [3.33933457e-01 3.00209166e+02]]
[[ -899.10927009  -900.44358034]
 [ -898.77568954 -2098.33254382]]
[[ 899.11001302  899.44356017]
 [ 898.10949944 2398.6527806 ]]
[-2.63367457e+25 -3.26112890e+17]
[2.36796321e+28 2.36532823e+28]
[ 5.31110445e+87 -1.12144995e+59]
x_t1 [2.36796321e+28 2.36532823e+28]
y:  [ 5.31110445e+87 -1.12144995e+59]
s:  [2.36796321e+28 2.36532823e+28]
[[899.11001302 898.10951802]
 [898.109

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: RuntimeWarning: overflow encountered in matmul
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:21: RuntimeWarning: overflow encountered in matmul
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in matmul
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: RuntimeWarning: overflow encountered in matmul
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: RuntimeWarning: invalid value encountered in matmul
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: RuntimeWarning: invalid value encountered in true_divide


ValueError: array must not contain infs or NaNs